/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <colors>

// - Enable/Disable "Fixes"
new Handle:g_hServerCVar             = INVALID_HANDLE;
new Handle:g_hPubBlock               = INVALID_HANDLE;

// - PubBlocker
new bool: bHandled = false;
new Handle: hTimer = INVALID_HANDLE;
new Handle: g_hReady = INVALID_HANDLE;

/*
* Version 1.0
* - Prevent Server CVar change Spam on Server Load.
* 
* Version 1.1
* - Integrated PubBlocker
* > Checks for l4d_ready_enabled cvar to decide whether to "activate"
* 
* - Added CVar Toggles for Functions
* */

public Plugin:myinfo = 
{
    name = "L4D2 Game/Server Tweaks&Fixes",
    author = "Sir",
    description = "What Name says",
    version = "1.1",
}

public OnPluginStart()
{
    //CVars.
    g_hServerCVar = CreateConVar("GSTF_ServerCVar", "1", "Block Server CVar Changes being Broadcasted?");
    g_hPubBlock = CreateConVar("GSTF_BlockPub", "1", "Only allow Competitive Games on Server?");
    g_hReady = FindConVar("l4d_ready_enabled");
    
    //Server CVar
    HookEvent("server_cvar", Event_ServerCvar, EventHookMode_Pre);
    
    AutoExecConfig(true, "GSTF");
}

//Server Cvar
//-----------
public Action:Event_ServerCvar(Handle:event, const String:name[], bool:dontBroadcast)
{
    if(GetConVarBool(g_hServerCVar)) return Plugin_Handled;
    return Plugin_Continue;
}

//Block Non-Competitive Games
//---------------------------
public OnClientPostAdminCheck(client)
{
    if(!GetConVarBool(g_hPubBlock) || bHandled || GetConVarBool(g_hReady)) return;
    
    if(IsValidClient(client) && !IsFakeClient(client))
    {
        bHandled = true;
        CreateTimer(25.0, NotifyPubs, _, TIMER_REPEAT);
        hTimer = CreateTimer(150.0, KickPubs);
    }
}

public OnClientDisconnect_Post(client)
{
    if(GetRealClientCount() != 0) Handled();
}

public Action:NotifyPubs(Handle:timer)
{
    if(!bHandled) return Plugin_Stop;
    
    CPrintToChatAll("{default}[{blue}PubBlocker{default}] {blue}Only use this server for {default}Competitive Play")
    CPrintToChatAll("{default}[{blue}PubBlocker{default}] {blue}Everyone will be kicked unless a {default}!match {blue}config is loaded")
    return Plugin_Continue;
}

public Action:KickPubs(Handle:timer)
{
    ServerCommand("sm_kick @all Only Competitive Play on this Server");
    Handled();
}

bool:IsValidClient(client)
{
    if (client <= 0 || client > MaxClients) return false;
    if (!IsClientInGame(client)) return false;
    if (IsClientSourceTV(client) || IsClientReplay(client)) return false;
    return true;
}

GetRealClientCount() 
{
    new clients = 0;
    for (new i = 1; i <= GetMaxClients(); i++) 
    {
        if(IsClientInGame(i) && IsClientConnected(i) && !IsFakeClient(i)) clients++;
    }
    return clients;
}

Handled()
{
    bHandled = false;
    if (hTimer != INVALID_HANDLE)
    {
        KillTimer(hTimer);
        hTimer = INVALID_HANDLE;
    }
}
